blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/cxdzc/TornAPIWrapper/discussions
    about: Ask and answer questions here.
  - name: Other
    url: https://github.com/cxdzc/TornAPIWrapper/discussions
    about: Chat, share ideas, or take polls.
